### PR TITLE
Log out buttons

### PR DESCRIPTION
**Pull request by IgalRedd**
Added log out buttons for all the views as well as updated main to ensure this works.

Also fixed some issues in the views of some of the classes that were using System.out

### CODE REVIEW

**Review by andriiostrolutskyi — APPROVED** [review]

**Review by jacobdesousa — CHANGES_REQUESTED** [review]
Please make it so the user session is cleared when the user logs out

**Review by elinsooon — DISMISSED** [review]

**Review by andriiostrolutskyi — DISMISSED** [review]

**Review by jacobdesousa — APPROVED** [review]

**Comment by tadanokaida** [comment]
The logout buttons function well, just have to change the positioning of the logout button, since it covers the table of information in the store and warehouse user main menus

**Review by tadanokaida — DISMISSED** [review]
Buttons work as intended and are positioned well

**Review by tadanokaida — APPROVED** [review]

**Review by jacobdesousa — DISMISSED** [review]
Reapproved after position change

**Review by jacobdesousa — APPROVED** [review]
Approved

**Review by andriiostrolutskyi — APPROVED** [review]

**Pull request merged**
