### PR TITLE
main menu documentation

### PR DESCRIPTION
**Pull request by elinsooon**
added documentation comments to all main menu classes, removed testing files for main menus

### CODE REVIEW

**Review by jacobdesousa — DISMISSED** [review]
Removed extra code comments, fixed warnings. Comments on main menu classes are useful and well formatted. Thanks.

**Review by tadanokaida — APPROVED** [review]
Added appropriate comments to main menu classes

**Review by andriiostrolutskyi — DISMISSED** [review]

**Review by tadanokaida — DISMISSED** [review]

**Review by jacobdesousa — APPROVED** [review]
Re-approve after fixing merge conflicts.

**Review by jacobdesousa — APPROVED** [review]
Documentation looks good. Approved.

**Review by andriiostrolutskyi — APPROVED** [review]

**Review by tadanokaida — APPROVED** [review]

**Pull request merged**
